import { IImplementation } from '../common/models/Implementation';

export const implementation: IImplementation = {
  highest_num: 30,
  low_num: 2,
  info: [
    {
      school_id: 309,
      school: {
        is_subschool: true,
        sub_id: 12,
        id: 109,
        school_name: 'AET Test School',
        stage: '',
        consultant: '',
        progress: null,
        notes: '',
        status: 'none',
      },
      sub_schools: [
        {
          id: 110,
          sub_id: 12,
          is_subschool: true,
          school_name: 'test',
          stage: 'Assessment 2',
          consultant: 'NickyJohn',
          progress: 20,
          notes: '',
          status: 'none',
        },
        {
          id: 111,
          sub_id: 13,
          school_name: 'Hybrid Test School',
          stage: 'Assessment 1',
          consultant: 'NickyJohn',
          is_subschool: true,
          progress: 20,
          notes: '',
          status: 'champion',
        },
      ],
    },
    {
      school_id: 310,
      school: {
        sub_id: 12,
        id: 209,
        is_subschool: true,
        school_name: 'AET Test School',
        stage: 'Assessment 1',
        consultant: 'NickyJohn',
        progress: 0,
        notes: '',
        status: 'none',
      },
      sub_schools: [
        {
          id: 210,
          is_subschool: true,
          sub_id: 21,
          school_name: 'Hybrid Test School',
          stage: 'Assessment 1',
          consultant: 'NickyJohn',
          progress: 20,
          notes: '',
          status: 'champion',
        },
      ],
    },
    {
      school_id: 311,
      school: {
        sub_id: 12,
        id: 211,
        is_subschool: true,
        school_name: 'AET Test School',
        stage: 'Assessment 1',
        consultant: 'NickyJohn',
        progress: 50,
        notes: '',
        status: 'none',
      },
      sub_schools: [],
    },
  ],
  slider: [
    { id: 1, label: 'Design Tutorial', school: 30 },
    { id: 2, label: 'Planning Tutorial', school: 10 },
    { id: 3, label: 'Assessment 1', school: 5 },
    { id: 4, label: 'Post Assessment Tutorial 1', school: 15 },
    { id: 5, label: 'Mid year Review', school: 2 },
    { id: 6, label: 'Assessment 2', school: 20 },
    { id: 7, label: 'Post Assessment Tutorial 2', school: 16 },
    { id: 8, label: 'Assessment 3', school: 12 },
    { id: 9, label: 'End of year review', school: 8 },
  ],
};
